CREATE TABLE business
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id    BIGINT,
    name        VARCHAR(255),
    description VARCHAR(255),
    location    VARCHAR(255),
    city        VARCHAR(255),
    phone       VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_business PRIMARY KEY (id)
);

ALTER TABLE business
    ADD CONSTRAINT uc_business_owner UNIQUE (owner_id);

ALTER TABLE business
    ADD CONSTRAINT FK_BUSINESS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES user_table (id);
CREATE INDEX idx_owner_id ON business (owner_id);
