CREATE TABLE user_table
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    role       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_table PRIMARY KEY (id)
);

ALTER TABLE user_table
    ADD CONSTRAINT uc_user_table_email UNIQUE (email);