CREATE TABLE business_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id    BIGINT,
    name        VARCHAR(255),
    description VARCHAR(255),
    location    VARCHAR(255),
    city        VARCHAR(255),
    phone       VARCHAR(255),
    created_at  date,
    CONSTRAINT pk_businessuser PRIMARY KEY (id)
);

ALTER TABLE business_user
    ADD CONSTRAINT FK_BUSINESSUSER_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

CREATE INDEX idx_owner_id
    ON business_user(owner_id);