CREATE TABLE service
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    duration    INTEGER                                 NOT NULL,
    price       DECIMAL,
    is_active   BOOLEAN                                 NOT NULL,
    business_id BIGINT,
    CONSTRAINT pk_service PRIMARY KEY (id)
);

ALTER TABLE service
    ADD CONSTRAINT FK_SERVICE_ON_BUSINESS FOREIGN KEY (business_id) REFERENCES business (id);