CREATE TABLE availability
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    business_id BIGINT,
    day_of_week VARCHAR(255),
    open_time   time WITHOUT TIME ZONE,
    close_time  time WITHOUT TIME ZONE,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_availability PRIMARY KEY (id)
);

ALTER TABLE availability
    ADD CONSTRAINT FK_AVAILABILITY_ON_BUSINESS FOREIGN KEY (business_id) REFERENCES business (id);

CREATE INDEX idx_business_id ON availability(business_id)