CREATE TABLE appointment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT,
    service_id  BIGINT,
    start_time  TIMESTAMP WITHOUT TIME ZONE,
    end_time    TIMESTAMP WITHOUT TIME ZONE,
    status      SMALLINT,
    notes       VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appointment PRIMARY KEY (id)
);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES user_table (id);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_SERVICE FOREIGN KEY (service_id) REFERENCES service (id);