spring.application.name=Backend

# DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/BookMe
spring.datasource.username=BookMe
spring.datasource.password=bookme_pass

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true